# Site Info
title: yphy's blog
tagline:
description: 'blog for studying'
url: http://yphy.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: yphy
  description:
  gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  contact:
    linkedin:
    github:    https://github.com/yphy
    facebook:  https://www.facebook.com/profile.php?id=100008275333472
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:yphy09@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://ratsgo.github.io/public/img/picture.JPG
  caption: Original Artwork &copy; Pablo Picasso. Girl before a Mirror. Boisgeloup, March 1932. Oil on canvas

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'yphy-github-io' # leave blank if you don't want disqus
